apiVersion: apps/v1
kind: Deployment
metadata:
  name: chef-deployment
  labels:
    app: kube-kitchen
    section: kitchen
spec:
  replicas: 1
  selector: 
    matchLabels:
      job: chef
  template:
    metadata: 
      labels:
        app: kube-kitchen
        section: kitchen
        job: chef
    spec:
      containers:
      - name: chef
        image: joellord/kk-chef:latest
        ports: 
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: chef-service
  labels:
    app: kube-kitchen
    section: kitchen
    description: pass
spec:
  type: NodePort
  selector:
    job: chef
  ports:
  - port: 3000
    nodePort: 32300
