apiVersion: apps/v1
kind: Deployment
metadata:
  name: bar-deployment
  labels:
    app: kube-kitchen
    section: bar
spec:
  replicas: 2
  selector: 
    matchLabels:
      job: barman
  template:
    metadata: 
      labels:
        app: kube-kitchen
        section: bar
        job: barman
    spec:
      containers:
      - name: bar
        image: joellord/kk-bar:latest
        ports: 
        - containerPort: 3000
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 3
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: 3000
          initialDelaySeconds: 3
          periodSeconds: 3