apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fridge-pvc
  labels:
    app: kube-kitchen
    section: kitchen
    job: fridge
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
