apiVersion: apps/v1
kind: Deployment
metadata:
  name: cook-deployment
  labels:
    app: kube-kitchen
    section: kitchen
spec:
  replicas: 2
  selector: 
    matchLabels:
      job: cook
  template:
    metadata: 
      labels:
        app: kube-kitchen
        section: kitchen
        job: cook
    spec:
      containers:
      - name: cook
        image: joellord/kk-cook:latest
        ports: 
        - containerPort: 3000
