apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: front-ingress
  labels:
    app: kube-kitchen
    section: front
    job: maitred
spec:
  backend:
    serviceName: front-service
    servicePort: 80

# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: front-ingress
#   labels:
#     app: kube-kitchen
#     section: front
#     job: maitred
# spec:
#   rules:
#   - http:
#       paths: 
#         - path: /
#           pathType: Prefix
#           backend:
#             service:
#               name: front-service
#               port:
#                 number: 80