apiVersion: v1
kind: Service
metadata:
  name: front-service
  labels:
    app: kube-kitchen
    section: front
    description: maitre-d
spec:
  selector:
    job: waiter
  ports:
    - port: 80
      protocol: TCP
